### ISSUE TITLE
the sides of the modal are not clickable

### ISSUE THREAD

**Issue by QuesoCaliente** [pheralb/superkey#14]
Hello everyone, recently using the library I realized that it is not possible to close the modal window by clicking on the sides, I did a pr to solve this, I hope it can be considered, thanks

![image](https://user-images.githubusercontent.com/43506340/215570351-6edb0374-9d5d-45a9-bbdd-86ce05f07fbf.png)

PR: https://github.com/pheralb/superkey/pull/13

**Comment by pheralb** [comment]
🎉 Fixed in [v0.2.1](https://github.com/pheralb/superkey/releases/tag/v0.2.1).

Thanks for the report 🚀
